server:
  port: 1170

spring:
  #autoconfigure:
  #exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/laboratory?useUnicode=true&characterEncoding=UTF-8&userSSL=false&serverTimezone=UTC
    password: 114130
    username: root
  redis:
    password: 123465
    host: 127.0.0.1
    database: 0
    port: 6379

logging:
  config: classpath:logback-pigeon.xml

pigeon:
  knife4j:
    title: Lab在线接口文档 - 0.1.0
    group: ''
    description: Lab 在线接口文档
    version: 1.0
    contact:
      name: yiidii
      url: 'https://blog.yiidii.cn'
      email: 'yd1141309981@gmail.com '
  log:
    ali:
      endpoint: cn-beijing.log.aliyuncs.com
      accessKeyId: LT******Wv
      accessKeySecret: b0******z3
      project: xxx
      logStore: xxx
    path: logs
    level: INFO
  strategy:
    base-package: cn.yiidii.openapi
  netty:
    wsChat:
      server:
        path: /ws/im
        port: 7880
    agent:
      server:
        port: 7890
        idleTime: 10
