server:
  port: 1170

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: '@project.artifactId@'
  profiles:
    active: '@profile.active@'

pigeon:
  knife4j:
    title: Lab在线接口文档 - 0.1.0
    group: ''
    description: Lab 在线接口文档
    version: 1.0
    contact:
      name: yiidii
      url: 'https://blog.yiidii.cn'
      email: 'yd1141309981@gmail.com '
  log:
    path: logs
    level: info
  strategy:
    base-package: cn.yiidii.openapi
  ignore-urls:
    - '/oauth/token'
    - '/doc.html'
    - '/webjars/css/**'
    - '/webjars/js/**'
    - '/v2/api-docs'
    - '/swagger-resources'
    - '/favicon.ico'
    - '/accessRecord/**'
    - '/jd/**'
    - '/telecom/**'
    - '/wm/**'
    - '/free/**'
  trace:
    enabled: true

mybatis-plus:
  sql-log:
    enable: true